#!/usr/bin/env bash
# Displays DNS A record info for a domain and its subdomains

domain=$1
subdomain=$2

get_info() {
  local sub=$1
  local output
  output=$(dig +short A ${sub}.${domain})
  if [ -n "$output" ]; then
    echo "The subdomain ${sub} is a A record and points to ${output}"
  fi
}

if [ -z "$domain" ]; then
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi

if [ -z "$subdomain" ]; then
  for sub in www 98.93.160.232 35.175.152.228 44.202.81.191; do
    get_info "$sub"
  done
else
  get_info "$subdomain"
fi
